### ISSUE TITLE
On the use of ip address instead of port forwarding

### ISSUE THREAD

**Issue by ricog** [loadsys/CakePHP-Skeleton#68] opened 2015-01-30 02:39 UTC
We already disabled port forwards in the new skeleton puphpet config, but I wanted to bring it to everyone's attention.

My team does not use port forwarding because we always had conflicts. I know Brian's team has previously mentioned only using 1 VM at a time, but my team has 9 or more active projects that we sometimes need to jump around in. That meant trying to manage different ports for each.

Instead we are using the IP directly, and optionally adding entries to our /etc/hosts file. The IP needs to be unique anyway (if you access multiple VMs at a time). This is just as accessible as a port forward, and has the advantage that the app is actually running on the same ports as production.

**Comment by beporter** [comment] 2015-01-30 03:09
It doesn't work for me because I access the VMs from my PC, not my Mac. There is no route for my PC to address the VM unless we switch to NAT based IPs for the VM that will resolve on our home networks. The port forward means I can access port 8080 on my Mac's LAN IP to get to the running VM. I suspect I will have to spend some (a lot) of time now to set up an appropriate proxy on my Mac to forwards requests to the right private IP. Can't argue against the good of the group.

**Comment by alecho** [comment] 2015-01-30 19:24
How hard would NAT IPs be to setup with the vagrant?

**Comment by beporter** [comment] 2015-01-30 19:27
It was already a part of the old skeleton. But doing it reliably across all of our configs might take some testing and tweaking.

**Comment by beporter** [comment] 2015-01-30 19:28
Oh, and we'll still have problems because we can't specify a single static IP because all of our internal networks don't match, and we can't use DHCP because then your hosts files wouldn't stay accurate between boots. So yeah, it's not going to work very well.

**Comment by ricog** [comment] 2015-01-30 20:12
@beporter what about an optional wrapper script that would add your desired port forwards when you bring a machine up? Most devs wouldn't need it, but anyone wanting to access their VMs remotely could use it.

**Comment by beporter** [comment] 2015-01-30 20:16
I thought we were solving this problem by making the port forwards auto-correctable, but yeah if that's not gonna work I'm just gonna have to deal with it somehow on my own. I'm not thrilled about having to come up with a way to override the config.yaml conditionally.

**Comment by beporter** [comment] 2015-01-30 21:07
I'm also not sure how you'd make such a wrapper script. What did you have in mind.

**Comment by beporter** [comment] 2015-02-17 19:10
I've confirmed that VMware is capable of auto-correct conflicting port forwards when resuming a suspended VM, but VirtualBox currently is not (this is in spite of the fact that it's possible to manually reassign the port forwards for a suspended VirtualBox VM using the `VBoxManage vmmodify` command or the GUI app.)

There is a vagrant issue about it, with conflicting information: https://github.com/mitchellh/vagrant/issues/1740#issuecomment-74574056

**Comment by beporter** [comment] 2015-10-20 19:35
I'm going to close this, since I think the current skeleton gives us most of the best of both worlds. The port forwards _will_ conflict by default between VMs, but they will also auto-correct, which is good enough for my team. I'm also adding auto-IP-token replacement in #158 to prevent the majority of overlap.

**Closed by beporter** 2015-10-20 19:35 UTC
Labels: question
